[build]
publish = "."

[build.environment]
NODE_VERSION = "16"

# Przekierowania dla wersji angielskiej
[[redirects]]
  from = "https://www.academyofsouls.com/*"
  to = "https://academyofsouls.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en"
  to = "/index-en.html"
  status = 301
  force = true

[[redirects]]
  from = "/en/*"
  to = "/index-en.html"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/index-en.html"
  status = 200
  conditions = {host = ["academyofsouls.com", "www.academyofsouls.com"]}

# Przekierowania dla wersji polskiej
[[redirects]]
  from = "https://www.akademiadusz.com/*"
  to = "https://akademiadusz.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  conditions = {host = ["akademiadusz.com", "www.akademiadusz.com"]}

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

# Nagłówki bezpieczeństwa i cache
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; font-src 'self' https: data:;"
