[build]
publish = "."

[build.environment]
NODE_VERSION = "16"

# Przekierowania dla academyofsouls.com
[[redirects]]
  from = "https://www.academyofsouls.com/*"
  to = "https://academyofsouls.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://academyofsouls.com/"
  to = "https://academyofsouls.com/en/"
  status = 302
  conditions = {Language = ["en"]}

[[redirects]]
  from = "https://academyofsouls.com/*"
  to = "https://academyofsouls.com/:splat"
  status = 200

# Przekierowania dla akademiadusz.com
[[redirects]]
  from = "https://www.akademiadusz.com/*"
  to = "https://akademiadusz.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://akademiadusz.com/"
  to = "https://akademiadusz.com/index.html"
  status = 200

[[redirects]]
  from = "https://akademiadusz.com/*"
  to = "https://akademiadusz.com/:splat"
  status = 200

# Domyślne przekierowanie
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Nagłówki bezpieczeństwa i cache
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; font-src 'self' https: data:;"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
